//USER
export const LOGIN = 'LOGIN';
export const OPEN_LOGIN = 'OPEN_LOGIN';
export const REGISTER = 'REGISTER';
export const FETCH_USER_DATA = 'FETCH_USER_DATA';
export const FETCH_OWN_DATA = 'FETCH_OWN_DATA';
export const NEW_NOTIFICATION = 'NEW_NOTIFICATION';
export const LOAD_INSTAGRAM_IMAGES = 'LOAD_INSTAGRAM_IMAGES';
export const LIKE_INSTAGRAM_MEDIA = 'LIKE_INSTAGRAM_MEDIA';
export const CREATE_INSTAGRAM_COMMENT = 'CREATE_INSTAGRAM_COMMENT';

export const PROMOTE_POST = 'PROMOTE_POST';
export const LOAD_FAMELAB_USER_CONTENT = 'LOAD_FAMELAB_USER_CONTENT';
export const LOAD_LEADERBOARD = 'LOAD_LEADERBOARD';
export const LOAD_MEDIA_AND_COMMENTS = 'LOAD_MEDIA_AND_COMMENTS';
export const WILL_LIKE_COMMENT = 'WILL_LIKE_COMMENT';
export const LIKE_COMMENT = 'LIKE_COMMENT';
export const WILL_UNLIKE_COMMENT = 'WILL_UNLIKE_COMMENT';
export const UNLIKE_COMMENT = 'UNLIKE_COMMENT';

export const RECEIVE_INSTAGRAM_FRIENDS = 'RECEIVE_INSTAGRAM_FRIENDS';

// CONTACTS
export const FETCH_CONTACTS = 'FETCH_CONTACTS';
export const RECEIVE_CONTACTS = 'RECEIVE_CONTACTS';
export const RECEIVE_CONTACTS_FAILURE = 'RECEIVE_CONTACTS_FAILURE';

// CONTENT
export const SUBMIT_CONTENT = 'SUBMIT_CONTENT';
export const FETCH_CONTENT = 'FETCH_CONTENT';
export const HEART_COMMENT = 'HEART_COMMENT';


// EACH CONTENT
export const PASS_ON_POST = 'PASS_ON_POST';
export const COMMENT_ON_POST = 'COMMENT_ON_POST';
export const LIKE_POST = 'LIKE_POST';
